#!/usr/bin/env python3
# decode_book_any.py
"""
Decode a BookRecord protobuf stored in Cassandra (or decode from hex).

Usage:
  # decode by primary key (connects to Cassandra)
  python decode_book_any.py row --tenant TENANT --store STORE_UUID --category CATEGORY --book BOOK_UUID

  # decode from hex (no DB)
  python decode_book_any.py hex --hex 0x0a1647...

Env vars (optional):
  CASSANDRA_CONTACT_POINT (default: 192.168.0.223)
  CASSANDRA_PORT (default: 9042)
  CASSANDRA_KEYSPACE (default: taulu_testing)
  CASSANDRA_USERNAME (default: cassandra)
  CASSANDRA_PASSWORD (default: cassandra)
"""
import os
import sys
import argparse
import uuid
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import book_record_pb2  # ensure this file exists (generated by protoc)

# Config from env (overridable)
CONTACT_POINT = os.getenv("CASSANDRA_CONTACT_POINT", "192.168.0.223")
PORT = int(os.getenv("CASSANDRA_PORT", "9042"))
KEYSPACE = os.getenv("CASSANDRA_KEYSPACE", "taulu_testing")
USERNAME = os.getenv("CASSANDRA_USERNAME", "cassandra")
PASSWORD = os.getenv("CASSANDRA_PASSWORD", "cassandra")

def make_session():
    auth = None
    if USERNAME and PASSWORD:
        auth = PlainTextAuthProvider(username=USERNAME, password=PASSWORD)
    cluster = Cluster(contact_points=[CONTACT_POINT], port=PORT, auth_provider=auth)
    session = cluster.connect(KEYSPACE)
    return cluster, session

def decode_bytes(raw_bytes):
    br = book_record_pb2.BookRecord()
    br.ParseFromString(bytes(raw_bytes))
    return br

def print_br(br):
    print("Decoded BookRecord:")
    for fd, val in br.ListFields():
        print(f"  {fd.name}: {val}")

def from_cassandra(tenant_id, store_id, category, book_id):
    # convert uuid strings to uuid.UUID objects if necessary
    try:
        if isinstance(store_id, str):
            store_id = uuid.UUID(store_id)
        if isinstance(book_id, str):
            book_id = uuid.UUID(book_id)
    except Exception as e:
        print("Invalid UUID format:", e)
        return

    cluster, session = make_session()
    try:
        cql = """SELECT book_record FROM my_bookstore_example
                 WHERE tenant_id=%s AND store_id=%s AND category=%s AND book_id=%s"""
        row = session.execute(cql, (tenant_id, store_id, category, book_id)).one()
        if not row:
            print("No such row (check primary key types/values).")
            return
        br = decode_bytes(row.book_record)
        print_br(br)
    finally:
        cluster.shutdown()

def from_hex(hexstr):
    h = hexstr[2:] if hexstr.startswith("0x") else hexstr
    try:
        raw = bytes.fromhex(h)
    except Exception as e:
        print("Invalid hex:", e)
        return
    br = decode_bytes(raw)
    print_br(br)

def main():
    p = argparse.ArgumentParser(prog="decode_book_any.py")
    sub = p.add_subparsers(dest="cmd", required=True)

    c1 = sub.add_parser("row", help="Decode row by primary key (reads from Cassandra)")
    c1.add_argument("--tenant", required=True, help="tenant_id (text)")
    c1.add_argument("--store", required=True, help="store_id (uuid)")
    c1.add_argument("--category", required=True, help="category (text)")
    c1.add_argument("--book", required=True, help="book_id (uuid)")

    c2 = sub.add_parser("hex", help="Decode from hex blob (no DB connection)")
    c2.add_argument("--hex", required=True, help="Hex string (0x.... or without 0x)")

    args = p.parse_args()

    if args.cmd == "row":
        from_cassandra(args.tenant, args.store, args.category, args.book)
    elif args.cmd == "hex":
        from_hex(args.hex)
    else:
        p.print_help()

if __name__ == "__main__":
    main()
