#!/usr/bin/env python3
"""
read_random_book.py

Usage examples:
  # pick randomly from a small sample (safe for small/medium tables)
  python read_random_book.py --method sample --sample-size 50

  # pick randomly by token (better for large datasets / partition-level randomness)
  python read_random_book.py --method token

Environment variables:
  CASSANDRA_CONTACT_POINTS (comma separated, default 127.0.0.1)
  CASSANDRA_PORT (default 9042)
  CASSANDRA_KEYSPACE (default taulu_testing)
  CASSANDRA_USERNAME
  CASSANDRA_PASSWORD
  CASSANDRA_USE_SSL (true/false)
  CASSANDRA_CA_CERT (path to cert if using SSL)
"""

import os
import random
import ssl
import argparse
from datetime import datetime
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import book_record_pb2  # generated by: protoc --python_out=. book_record.proto

# --- Config from env ---
CONTACT_POINTS = os.getenv("CASSANDRA_CONTACT_POINTS", "127.0.0.1").split(",")
PORT = int(os.getenv("CASSANDRA_PORT", "9042"))
KEYSPACE = os.getenv("CASSANDRA_KEYSPACE", "taulu_testing")
USERNAME = os.getenv("CASSANDRA_USERNAME", None)
PASSWORD = os.getenv("CASSANDRA_PASSWORD", None)
USE_SSL = os.getenv("CASSANDRA_USE_SSL", "false").lower() == "true"
CA_CERT = os.getenv("CASSANDRA_CA_CERT", None)

TABLE = "my_bookstore_example"

# ---- Connection helper ----
def make_session():
    auth_provider = None
    if USERNAME and PASSWORD:
        auth_provider = PlainTextAuthProvider(username=USERNAME, password=PASSWORD)

    ssl_options = None
    if USE_SSL:
        if not CA_CERT:
            raise RuntimeError("CASSANDRA_CA_CERT required when CASSANDRA_USE_SSL=true")
        ssl_ctx = ssl.create_default_context(cafile=CA_CERT)
        ssl_options = {'ssl_context': ssl_ctx}

    cluster = Cluster(contact_points=CONTACT_POINTS, port=PORT, auth_provider=auth_provider, ssl_options=ssl_options)
    session = cluster.connect(KEYSPACE)
    return cluster, session

# ---- Strategy 1: sample a small batch and pick randomly ----
def get_random_by_sample(session, sample_size=50):
    """
    Fetch up to `sample_size` rows and pick one at random.
    Good for demos and small tables.
    """
    cql = f"SELECT tenant_id, store_id, category, book_id, updated_at, book_record FROM {TABLE} LIMIT {sample_size}"
    rows = session.execute(cql)
    rows_list = list(rows)
    if not rows_list:
        return None
    return random.choice(rows_list)

# ---- Strategy 2: token-based random partition selection ----
def get_random_by_token(session):
    """
    Use token() to select a random partition (works when your partition key is (tenant_id, store_id)).
    This performs a single lightweight read and is more suitable for large datasets.
    """
    # Cassandra Murmur3 token range for vnodes (signed 64-bit)
    MIN_TOKEN = -9223372036854775808
    MAX_TOKEN = 9223372036854775807
    random_token = random.randint(MIN_TOKEN, MAX_TOKEN)

    # Query for any row whose partition token is greater than a random token (wrap-around if needed)
    # Note: token(tenant_id, store_id) usage assumes your partition key is (tenant_id, store_id)
    cql = (
        f"SELECT tenant_id, store_id, category, book_id, updated_at, book_record "
        f"FROM {TABLE} WHERE token(tenant_id, store_id) > {random_token} LIMIT 1"
    )
    rows = session.execute(cql)
    row = rows.one()
    if row is not None:
        return row

    # wrap-around: get the first row in token order
    cql_wrap = f"SELECT tenant_id, store_id, category, book_id, updated_at, book_record FROM {TABLE} LIMIT 1"
    rows = session.execute(cql_wrap)
    return rows.one()

# ---- Helper to pretty-print protobuf BookRecord ----
def print_book_record(row):
    if row is None:
        print("No row found.")
        return

    try:
        br = book_record_pb2.BookRecord()
        # row.book_record is expected to be bytes/bytearray
        br.ParseFromString(row.book_record)
    except Exception as e:
        print("Failed to parse protobuf:", e)
        # Still print row metadata
        print("tenant:", getattr(row, "tenant_id", None))
        print("store_id:", getattr(row, "store_id", None))
        print("category:", getattr(row, "category", None))
        print("book_id:", getattr(row, "book_id", None))
        print("updated_at:", getattr(row, "updated_at", None))
        return

    print("----- Random Book -----")
    print("tenant:", row.tenant_id)
    print("store_id:", row.store_id)
    print("category:", row.category)
    print("book_id:", row.book_id)
    print("updated_at:", row.updated_at)
    print("")
    # Print the protobuf fields in a friendly way
    # If message has many fields, adjust accordingly
    # Using the generated API; unknown fields won't break this.
    for field_descriptor, value in br.ListFields():
        name = field_descriptor.name
        print(f"{name}: {value}")
    print("-----------------------")

# ---- CLI ----
def main():
    parser = argparse.ArgumentParser(description="Read a random BookRecord from Cassandra and print the deserialized protobuf.")
    parser.add_argument("--method", choices=["sample", "token"], default="sample",
                        help="How to pick a random row. 'sample' reads a small batch; 'token' uses token() for partition randomness.")
    parser.add_argument("--sample-size", type=int, default=50, help="Number of rows to fetch for sample method.")
    args = parser.parse_args()

    cluster = None
    try:
        cluster, session = make_session()

        if args.method == "sample":
            row = get_random_by_sample(session, sample_size=args.sample_size)
        else:
            row = get_random_by_token(session)

        print_book_record(row)

    except Exception as exc:
        print("Error:", exc)
    finally:
        if cluster:
            cluster.shutdown()

if __name__ == "__main__":
    main()
